version: 1
accounts:
- name: user
  coins:
  - 20000token
  - 200000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: user
  coins:
  - 5token
  - 100000stake
validators:
- name: user
  bonded: 100000000stake

